# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4418d748c6738fe15a0d626d3e77cb2289f3bb892f23969e7ec6e94efa4b6021702a6510f6d4e99c2df505c2d8afd03b6d03a28c888e4303c385c63e247f2dff

test:
  secret_key_base: 4212aa4929e3a3b2f860f8328c48bde0f5e835e07b76f2ca7b7a739f0b0dcba5de3c235ae2806ba6af1fb73f73b7de03ea43895a8df3d100fcae99fa638a20b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
